### ISSUE TITLE
Refactor announcement.go to achieve better response times and less error rates

### ISSUE THREAD

**Issue by GetPsyched** [NIT-KKR-Student-Support-System/nkss-backend#5]
## The problem
As of now, all the processing is done in each GET request that's sent to this API. This isn't ideal. On top of this, a same response requires the entire process to be repeated and the status of the response depends on an external website.

## The solution
- A database which stores the announcements and their hashes
- On a GET request to this API, assume the data in the database is fresh and return the results

### The cron script
- Compare the hash of the HTML page from the previous stored hash to check if it was modified
  - If not, do nothing
  - If it has changed, parse the HTML and store the data in the HTML table updating the individual hashes of each announcement if they have changed as well.

## Advantages
- An immediate response to the user
- No processing/db writes done in a GET request
- Removed dependency from an external source

**Comment by gotlougit** [comment]
One plan of action could be:

- Current ```GetAnnouncements()``` function does not return a HandlerFunc but rather does an insert into the database into a table with suitable schema. Care must be taken to only insert new records into the database instead (perhaps a UNIQUE constraint can do?)

- A new GetAnnouncements() will pretty much use the database as a cache to fetch the annoucements.

There can be a couple different ways to handle updating the "cache": A separate process from the server middleware that runs at regular intervals, a goroutine, or just having GetAnnouncements() run the scraping operation as and when it deems necessary to do so

**Comment by GetPsyched** [comment]
Referring to your first point, this will be combined with the undermentioned `goroutine`-like funtion, right?

**Comment by gotlougit** [comment]
I was thinking more of a global goroutine that runs maybe in off hours based on certain heuristics

**Comment by GetPsyched** [comment]
I got that. I'm not asking about when the goroutine will run. I mean will the insertion mentioned here be done inside said goroutine?

>     * Current `GetAnnouncements()` function does not return a HandlerFunc but rather does an insert into the database into a table with suitable schema

**Comment by gotlougit** [comment]
Yes, the goroutine would run the insert operation, so would be the same function

**Comment by gotlougit** [comment]
PR #14 should fix this issue
